runtime: python310
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # NOTE: While you can put non-secret env vars here, 
  # for secrets like API Keys, it is better to use Secret Manager 
  # or set them via command line during deployment.
  # For simplicity in this demo, you can replace the placeholder below,
  # BUT DO NOT COMMIT REAL KEYS TO PUBLIC REPOS.
  GEMINI_API_KEY: "AIzaSyBYQFPJfKSO_t7rzv4S17Jf-URlMUpRYcA"
